### PR TITLE
Add ä en Ä to charsArray

### PR DESCRIPTION
**Pull request by jorenvanhee**

### CODE REVIEW

**Comment by danielstjules** [comment]
Thanks for the PR! We already translate `ä => ae` In what languages do you feel this is incorrect, and `a` should be preferred? We've concluded that toAscii needs to be locale-sensitive, so a later release will need to support different mappings

**Comment by danielstjules** [comment]
Going to close for now in reference to https://github.com/danielstjules/Stringy/issues/116 But would appreciate any additional feedback as well!

**Comment by jorenvanhee** [comment]
Ah I see. My use case was different. I needed the ascii conversion for search. If someone searches for farm, färm should come up. Not something this repo should worry about :)

**Comment by danielstjules** [comment]
Gotcha! This might be helpful: https://github.com/danielstjules/Stringy#toascii-string-language--en--bool-removeunsupported--true-

**Pull request closed without merging**
