### PR TITLE
Add Stringy->hasUpperCase, Stringy->hasLowerCase along with StaticString counterparts & tests.

### PR DESCRIPTION
**Pull request by takobell**
These methods check if *any* part of the string has an upper or lower case character in it.

### CODE REVIEW

**Comment by takobell** [comment]
Any thoughts on this? Seems to fit in pretty well with the spirit of Stringy to me.

**Comment by danielstjules** [comment]
You're right, it does seem like a good fit. I'm hesitant right now, as when I added the "is__" methods, we ended up with:
* isAlpha
* isAlphanumeric
* isBlank
* isHexadecimal
* isJson
* isLowerCase
* isSerialized
* isUpperCase

I'm just trying to think of what other "has__" methods would be possible, and whether or not we could avoid adding a bunch of related ones.

**Comment by takobell** [comment]
Well... hasUpperCase and hasLowerCase are the two that made sense for my specific use-case.  But hasAlpha, hasAlphanumeric, hasBlank and hasHexadecimal seem like valid cases, too.

In this context, essentially "is" means "all" and "has" means "any".

In my mind, the only awkward ones are the ones that deal with data formats... i.e. hasJson and hasSerialized don't make sense.

**Comment by danielstjules** [comment]
After a bit more though, I'm fine with just having `hasUpperCase` and `hasLowerCase`. Thanks for the PR! :)

**Comment by vlakoff** [comment]
Thanks to this PR I have learned `mb_ereg_match()` matches from the beginning only ([php.net](http://php.net/manual/en/function.mb-ereg-match.php#86429) - [stackoverflow](http://stackoverflow.com/questions/6996909/perform-a-global-iterative-search-in-mb-ereg-match#6997010)), hence the `.*[[:lower:]]` patterns.

**Comment by takobell** [comment]
Yeah... added a few extra asserts in the tests to verify that because it was new to me too!

**Pull request merged**
