### PR TITLE
Support Full Unicode For Vietnamese.

### PR DESCRIPTION
**Pull request by anhskohbo**

### CODE REVIEW

**Comment by vlakoff** [comment]
Looks fine :)

a quick script for checking: https://gist.github.com/vlakoff/2f1acfa71068a4729033

**Comment by danielstjules** [comment]
Thanks for the PR @anhskohbo, and thanks for looking into patchwork compatibility @vlakoff. My only other concern is making sure all characters previously covered by Stringy are still present in the array. It's a bit hard to tell since things were re-ordered. I'll check it tonight, and once done, I'll merge it in. :)

**Comment by vlakoff** [comment]
That's one of the features of the script I posted above ;)

**Comment by anhskohbo** [comment]
I don't remove any characters. Just added and re-order :))

**Comment by danielstjules** [comment]
Just wanted to make sure nothing got missed, that's all. Thanks a lot for the PR! :)

**Pull request merged**
