### PR TITLE
[Proposal] Separate toAscii()'s charsArray to allow customization

### PR DESCRIPTION
**Pull request by vlakoff**
Again, this is just a proposal. Fairly related to #68.

I used a method instead of a property to not clutter the top of the file.
Very simple to extend:

    protected function charsArray()
    {
        $chars = parent::charsArray();
        // do stuff

        return $chars;
    }

Or, using some cache for optimal performances:

    protected function charsArray()
    {
        static $chars;

        if (!isset($chars)) {
            $chars = parent::charsArray();
            // do stuff
        }

        return $chars;
    }

### CODE REVIEW

**Comment by takobell** [comment]
Went to go create this exact pull request and pleasantly surprised to see that it already exists. The use case is we've got a wrapper method for Stringy's toAscii where we'd like merge in additional ASCII characters to consider.

**Comment by danielstjules** [comment]
I'd be more in support of this PR than what was proposed in #68, though they aren't technically achieving the same thing. This PR only allows you to handle characters not included in toAscii's set, while #68 also allows you to identify such characters.

**Comment by takobell** [comment]
> This PR only allows you to handle characters not included in toAscii's set.

That's exactly our requirement. 

The only things I'd change about this one is make `charsArray` a public method (for classes that aren't directly extending Stringy, like ours) and maybe a more explicit name.  `getCharsArray` or `asciiCharsArray` maybe.  `charsArray` is a bit too close to the existing `chars` for me.

**Comment by vlakoff** [comment]
* Right, #68 and this PR are supposed to be complementary.
* A thing to keep in mind, if later we change the format of `$charArray` it implies a BC break (or some kind of legacy support layer).

**Comment by vlakoff** [comment]
@takobell I'd rather keep the method protected, could you please provide more details about why you can make you way with a public but not a protected method?

**Comment by takobell** [comment]
@vlakoff In our case, we've got a bunch of static helper classes, one of them being StringHelper.  It extends a framework level BaseStringHelper class because there is existing functionality in there we need to incorporate into our app.  Our StringHelper additional is a wrapper for a bunch of calls to StaticStringy.

For example, we have a `StringHelper::getAsciiCharMap()`, which looks like this:

    public static function getAsciiCharMap()
    {
        if (!isset(static::$_asciiCharMap))
        {
            // Get the map from Stringy.
            $stringy = new Stringy();
            static::$_asciiCharMap = $stringy->asciiCharsArray();

            // Add in our ASCII punctuation mappings.
            ...
        }
    }

Obviously that won't work if the method is protected.

**Comment by danielstjules** [comment]
That could be solved by what's discussed in #68, avoiding the need to make it public

**Comment by vlakoff** [comment]
@takobell With your provided example, all you can do is get the $charArray and use its content for your own code, but not change the business logic of Stringy itself. Otherwise, we'd need to add some kind of reference storage and global state alteration, definitely not a good step. Also, this method is aimed at Stringy itself, not to provide the set of values for other code. Making it public would mean adding it to the API, and the benefits/cluttering ratio would be very bad IMO.

**Comment by vlakoff** [comment]
* Added a local cache for great performance gain.
* @danielstjules Do you have an opinion on the method name?

**Comment by takobell** [comment]
@vlakoff 

> With your provided example, all you can do is get the $charArray and use its content for your own code, but not change the business logic of Stringy itself.

Correct.  But in that particular example we'd want our custom logic and Stringy's `toAscii` implementation to be sharing the same underlying character mappings.  Yeah, there are some hacky workarounds I can do for it, but was just looking for something cleaner.

> Also, this method is aimed at Stringy itself, not to provide the set of values for other code.

Fair enough.  Maybe a better approach would be to let Stringy accept a user-supplied character mapping array that gets merged in with Stringy's internal one and keep the internal one protected?

@danielstjules 

> That could be solved by what's discussed in #68

Would it? Maybe I'm just overlooking how I'd be able to achieve the same thing.

**Comment by vlakoff** [comment]
@takobell So basically, you want to get and manipulate $charsArray at runtime. There are many ways to do it with the code of this PR. For an example see this gist: https://gist.github.com/vlakoff/0ebed93b6e853651661f

As a bonus, to easily extend from an existing Stringy instance: https://gist.github.com/vlakoff/7d6122564a0ec41d7e80. This technique has better performance than a true decorator (using composition and `__call()` magic).

**Comment by takobell** [comment]
@vlakoff Those examples work great if our class was extending Stringy directly.  But we're extending a separate base string helper class (for various reasons) and using our class as more of a facade/abstraction on top of Stringy in many methods.  A more complete example:

    class StringHelper extends BaseStringHelper
    {
        private $_asciiCharMap;

        // It's important that this method returns the character map that toAscii is also using, along
        // with some additional mappings.
        public static function getAsciiCharMap()
        {
            if (!isset(static::$_asciiCharMap))
            {
                // Get the map from Stringy.
                $stringy = new Stringy();
                static::$_asciiCharMap = $stringy->asciiCharsArray();

                // Add in our ASCII punctuation mappings.
                $static::$_asciiCharMap = array_merge($static::$_asciiCharMap, [
                    'bar' => ['foo']
                ]);
            }

            return static::$_asciiCharMap;
        }

        public static function toAscii($str)
        {
            return StaticStringy::toAscii($str);
        }
    }

**Comment by vlakoff** [comment]
This is perfectly doable. Just use only one (extended) Stringy instance, as a singleton, and not StaticStringy. Then, nothing prevents you from using an extended version of Stringy *inside* your own wrapper class.

**Comment by danielstjules** [comment]
@takobell Exactly what @vlakoff just mentioned.  :) You'd keep your custom helper class, but would have another class that extends stringy, exposing whatever details you'd like. So now you'd have `StringHelper`, `Stringy`, and `CustomStringy`, s.t. `CustomStringy` has a public `getCharsArray` method. 

I'd just rather not expose that array directly, as it limits flexibility in the future. A change in the format of the array would mean a breaking change, and require a new major release.

**Comment by takobell** [comment]
@vlakoff @danielstjules Well... now that you say it, it's perfectly obvious. :)

**Comment by danielstjules** [comment]
I'm happy with this PR :) Using a static var is a nice alternative to populating a static property at the top of the class.

**Comment by vlakoff** [comment]
Contrarily to a static property, you can even have several instances of `MyStringy` each with its own $charsArray, manipulated at runtime. The local static var doesn't introduce any side effect.

As a reminder, it's very simple to extend at class declaration, as shown in my first post.

**Pull request merged**
