### PR TITLE
Added php7 for travis

### PR DESCRIPTION
**Pull request by Big-Shark**
Added php7

### CODE REVIEW

**Comment by danielstjules** [comment]
Mind removing the allow_failures? I'd rather push out an immediate fix for isJSON. I like that it's now consistent with javascript. An empty string should not be accepted as valid JSON.

```
JSON.parse('');
(program):1 Uncaught SyntaxError: Unexpected end of input(…)
```

**Comment by Big-Shark** [comment]
Ok, I'll delete allow_failures

**Comment by danielstjules** [comment]
Thanks!

**Comment by danielstjules** [comment]
Fixed PHP7 via https://github.com/danielstjules/Stringy/commit/467375405473aca58d33c0469ca9d3c61d62768b

**Pull request merged**
