### PR TITLE
Changed travis infrastructure

### PR DESCRIPTION
**Pull request by Big-Shark**
See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/

### CODE REVIEW

**Comment by danielstjules** [comment]
It's already running on containers by default? https://travis-ci.org/danielstjules/Stringy/jobs/79595468

```
This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
```

**Comment by danielstjules** [comment]
Gonna close for now as I think it's unnecessary. But feel free to re-open if I'm wrong! :)

**Comment by Big-Shark** [comment]
This job ran on our legacy infrastructure. Please read our docs on how to upgrade
screenshot from 2015-09-10 11 45 11
http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure
>  For repos we recognize before 2015-01-01, linux builds are sent to our standard infrastructure.

Your first travis building was 2 years ago
https://travis-ci.org/danielstjules/Stringy/builds/8938830

**Comment by danielstjules** [comment]
Ok you win haha :)

Thanks again!

**Comment by Big-Shark** [comment]
Yippee! :tada: )

**Pull request merged**
