### PR TITLE
Added isBase64 method

### PR DESCRIPTION
**Pull request by mpociot**
I added support for a `isBase64` method to find out if a string is base64 encoded or not.

### CODE REVIEW

**Comment by danielstjules** [comment]
Thanks for the PR! I'm wondering why you're doing the check for empty string (`$this->str !== ''`) since it's technically valid input. Both PHP `base64_decode('', true);` and JS `atob('');` allow empty strings

**Comment by mpociot** [comment]
Hm..yeah I think you're right.

I just thought that a `s('')->isBase64()` seems kind of wrong to return null - because it's just an empty string, not a base64 encoded value.

Do you want me to modify the PR?

**Comment by lucasmichot** [comment]
Would love to get this in Stringy - any new on this @mpociot @danielstjules ?

**Comment by mpociot** [comment]
I'm waiting for feedback from @danielstjules

**Comment by danielstjules** [comment]
Sorry, thought I had pinged back here! I think I'd rather stay consistent with other standard libraries. So, `s('')->isBase64()` would return true. Hope you don't mind!

**Comment by lucasmichot** [comment]
Might be worth to add the method argument count to `\Stringy\StaticStringy::$methodArgs` too

**Comment by danielstjules** [comment]
Merged, thanks! :)

**Pull request closed without merging**
