### PR TITLE
Adding the option to trim the string with others characters, and define which trim function to use

### PR DESCRIPTION
**Pull request by kbca**
Adding the option to trim the string with others characters, not only with the default characters provided by php. Also added the option to define the function which will be used to trim the string, if it's normal trim, left trim or right trim

### CODE REVIEW

**Comment by danielstjules** [comment]
Thanks for PR! Would you mind adding some tests for this functionality?

**Comment by dudemelo** [comment]
:+1:

**Comment by kbca** [comment]
Added the tests and reforced the method to accept only trim, rtrim and ltrim.

**Comment by kbca** [comment]
Hey Dude, why didn't you accepted my pull request? I wrote the tests as you asked and wrote some more code to ensure the params sent to the function. Ok so, sorry for anything.

**Comment by danielstjules** [comment]
@kbca You added them 3 days ago, and I just got back from a trip this morning. Haven't gotten around to reviewing it since I've been at work all day. I appreciate your contribution, but please cut me some slack.

**Comment by kbca** [comment]
OK, sorry man. It was my mistake. I was viewing my fork and I saw there were modifications, 2 more commits, actually the commits I myself did. So I thought I was viewing your project, instead of my fork, but I just should have seen you didn't accepted nor rejected my pr. Anyway, sorry again and feel free to accept or reject wherever you are able to.

**Comment by danielstjules** [comment]
No worries - I hope I didn't offend you. And I really do appreciate your work on this. Just haven't had as much time for Stringy.

I squashed your commits and merged into master here: https://github.com/danielstjules/Stringy/commit/1a2e771ff8a9cb8cc240abbce7a63dd8613785fa (one of the commits seemed to be from a diff author)

I'm tempted to split this function out into trim, trimLeft and trimRight, as I think it might be nicer than using constants in this case.

Thanks again!

**Pull request closed without merging**
