### PR TITLE
Add link to PHP array manipulation lib in OOP way

### PR DESCRIPTION
**Pull request by bocharsky-bw**
I was inspired by Stringy and made a similar library in order to work with native PHP arrays in OOP way.

Could I add a partner link to my library in your README?

### CODE REVIEW

**Comment by danielstjules** [comment]
Hey! The library looks awesome. Any plans for PHP 5.3 support? That's been one of the biggest sellers for Stringy, since so many are stuck with legacy codebases, struggling to get to PHP 5.4

**Comment by bocharsky-bw** [comment]
@danielstjules You're right! I definitely should provide PHP 5.3 support, it's still used for legacy. Thanks a lot for this advice!

**Comment by GrahamCampbell** [comment]
:-1: No way PHP 5.3 should be supported.

**Comment by GrahamCampbell** [comment]
If you want to use php 5.3, use 1.x of this library.

**Comment by GrahamCampbell** [comment]
Anyone using PHP 5.4 or lower is frankly irresponsible since both no longer receive security fixes.

**Comment by bocharsky-bw** [comment]
@GrahamCampbell I meen to provide PHP 5.3 support for [Arrayzy](https://github.com/bocharsky-bw/Arrayzy) not for Stringy. Anyways, it's easy to achieve for Arrayzy now

**Comment by danielstjules** [comment]
> If you want to use php 5.3, use 1.x of this library.

We're not talking about Stringy :) And the 2.x version of the library hasn't broken compatibility since it hasn't needed to. Primary benefit would be to adopt traits to clean up the codebase.

> Anyone using PHP 5.4 or lower is frankly irresponsible since both no longer receive security fixes.

Whether or not that reflects the industry remains to be seen. http://w3techs.com/technologies/details/pl-php/5/all At the time of writing, that page suggests that ~70% of PHP-powered websites use 5.3/5.4. Without additional insight into their methodology, I can't suggest how accurate it is. But given the number of legacy CodeIgniter projects I've seen running on 5.2, this wouldn't surprise me.

**Comment by GrahamCampbell** [comment]
> At the time of writing, that page suggests that ~70% of PHP-powered websites use 5.3/5.4. 

They must be using the php version broadcast header. Anyone that is security concerned will have turned that off, so the server won't broadcast that it's running php. I also think that a lot of those servers reported are running wordpress, and that's generally a different type of user.

**Comment by danielstjules** [comment]
@GrahamCampbell

> They must be using the php version broadcast header.

Think you're right! :)

> Anyone that is security concerned will have turned that off, so the server won't broadcast that it's running php.

Given that it's on by default, I think you'd be surprised how many still return X-Powered-By PHP/5.x. That includes a lot of Laravel-powered sites/pages. A quickly google for laravel-related sites revealed a few:

* http://laravelsnippets.com/ PHP/5.6.7-1+deb.sury.org~precise+1
* https://larajobs.com/ PHP/5.5.14-1+deb.sury.org~trusty+1
* http://laraveles.com/foro/ PHP/5.5.24
* https://laracasts.com/ PHP/5.5.12-2+deb.sury.org~trusty+1
* https://laravel-news.com/ PHP/5.5.15-1+deb.sury.org~trusty+1
* https://imgubox.wnx.ch/ PHP/5.6.6
* http://screeenly.com/ PHP/5.6.6

But that's getting way off topic haha

> I also think that a lot of those servers reported are running wordpress, and that's generally a different type of user.

Given wordpress' marketshare, definitely right :) But I doubt they'd make up a majority.

**Comment by danielstjules** [comment]
Anyway, getting way off topic haha @bocharsky-bw Will checkout your lib this weekend :) Hope you don't mind, but I might move the link elsewhere

**Comment by GrahamCampbell** [comment]
> Given that it's on by default, I think you'd be surprised how many still return X-Powered-By PHP/5.x.

Yes. I'd say all those websites are missconfigured, and are at greater risk of getting hacked.

**Comment by GrahamCampbell** [comment]
https://styleci.io/ for example does not leak information about the server.

**Comment by danielstjules** [comment]
Yup, it's a trivial fix :)

**Comment by GrahamCampbell** [comment]
And http://laravel.com/ doesn't show the php version either. :)

**Comment by GrahamCampbell** [comment]
Infact, it was the default on my servers to have that turned off, so I suspect newer versions of php have this turned off more that old, skewing the stats.

**Comment by danielstjules** [comment]
> Infact, it was the default on my servers to have that turned off, so I suspect newer versions of php have this turned off more that old, skewing the stats.

That almost certainly depends on the package maintainers for your distro or container, rather than the PHP version, since it's still enabled by default

**Comment by GrahamCampbell** [comment]
Yeh, absolutely.

**Comment by bocharsky-bw** [comment]
@danielstjules OK, I'm looking forward! And I really don't mind if you move link somewhere, do on your own.

Anyway, thanks for your time, guys!

**Comment by bocharsky-bw** [comment]
Well, I declined PHP `5.3` support for now. The main reason is `5.3` don't support Traits. I think it'll be a big step back.
Maybe in future I create a separate branch for it, but I'm not sure.

And thank you guys for great discussion!

**Comment by danielstjules** [comment]
Didn't mean to sound pushy, was just asking :) Gonna close this for now though, as I'll be adding a new section for related libraries. I've gotten a few emails regarding similar projects

**Pull request closed without merging**
