### PR TITLE
Added matches() method. Issue #131.

### PR DESCRIPTION
**Pull request by Munawwar**
Please review.

### CODE REVIEW

**Comment by danielstjules** [comment]
Hi @Munawwar, thanks for the PR! Looks like tests are failing because of your use of the short array syntax. For this type of feature, I think we'd also want a few test cases if possible.

**Comment by Munawwar** [comment]
:smile: I was hoping that you'd take care of the rest (It is pretty unpolished I guess).
There were a few things on which I couldn't make up my mind - like 1. name of the method and 2. the interface -  should the matches be returned as array of normal strings or should it be an array of Stringy strings?

**Comment by danielstjules** [comment]
Gonna close this for now. I am hoping to expose a better API for matches/replace, etc, but I'd like to change the way regexps are handled in a new major. Thanks again! :)

**Comment by Munawwar** [comment]
:+1:

**Pull request closed without merging**
